// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1oyG34_F6wCp-Ot43ZiTHFz048WNuNSI',
    appId: '1:848726928029:web:dd3d8ccb4fa512b4ab4274',
    messagingSenderId: '848726928029',
    projectId: 'nextrade-56a46',
    authDomain: 'nextrade-56a46.firebaseapp.com',
    storageBucket: 'nextrade-56a46.firebasestorage.app',
    measurementId: 'G-SCLB5NSMGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3L8dgaZb2eWTjpGJxa9zN7SHC22HUF8',
    appId: '1:848726928029:android:93d4833af57e88d6ab4274',
    messagingSenderId: '848726928029',
    projectId: 'nextrade-56a46',
    storageBucket: 'nextrade-56a46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQi6NGEXodr1DD7-FQ5ZaSjr5zw-synOk',
    appId: '1:848726928029:ios:f7a887981642a3c6ab4274',
    messagingSenderId: '848726928029',
    projectId: 'nextrade-56a46',
    storageBucket: 'nextrade-56a46.firebasestorage.app',
    iosBundleId: 'com.example.nextrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQi6NGEXodr1DD7-FQ5ZaSjr5zw-synOk',
    appId: '1:848726928029:ios:f7a887981642a3c6ab4274',
    messagingSenderId: '848726928029',
    projectId: 'nextrade-56a46',
    storageBucket: 'nextrade-56a46.firebasestorage.app',
    iosBundleId: 'com.example.nextrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1oyG34_F6wCp-Ot43ZiTHFz048WNuNSI',
    appId: '1:848726928029:web:eacb09bea5616b27ab4274',
    messagingSenderId: '848726928029',
    projectId: 'nextrade-56a46',
    authDomain: 'nextrade-56a46.firebaseapp.com',
    storageBucket: 'nextrade-56a46.firebasestorage.app',
    measurementId: 'G-BD2PSEY96J',
  );
}
